import type { Topic, TopicId } from "@/types";

export const TOPICS: Record<TopicId, Topic> = {
  introductions: {
    id: "introductions",
    emoji: "👋",
    titleEN: "Introductions",
    titlePT: "Apresentações",
    descriptionPT: "Conheça pessoas novas e fale sobre você",
    difficulty: "beginner",
    starterMessage:
      "Hi! I'm so happy to chat with you today! Let's start — can you tell me a little about yourself? What's your name, and what do you do?",
    vocabularyHints: ["nice to meet you", "I work as", "I'm from", "I enjoy", "in my free time", "originally"],
    phraseSuggestions: [
      "My name is...",
      "I'm from Brazil.",
      "I work as a...",
      "I'm a student.",
      "I'm married / single.",
      "I have two kids.",
      "In my free time, I like...",
      "I enjoy watching series.",
      "I love thriller series!",
      "Nice to meet you!",
      "I'm learning English.",
    ],
  },
  "daily-life": {
    id: "daily-life",
    emoji: "☀️",
    titleEN: "Daily Life",
    titlePT: "Dia a Dia",
    descriptionPT: "Rotinas, hobbies e planos para o fim de semana",
    difficulty: "beginner",
    starterMessage:
      "Hey! How was your day today? Tell me all about it — I want to hear everything!",
    vocabularyHints: ["usually", "tend to", "routine", "habit", "lately", "recently", "on weekends"],
    phraseSuggestions: [
      "My day was good, thanks!",
      "I usually wake up at...",
      "In the morning, I...",
      "I like to watch series at night.",
      "I love thriller / comedy / drama series.",
      "My favorite show is...",
      "On weekends, I...",
      "I went to the supermarket.",
      "I cooked lunch at home.",
      "I was tired today.",
      "I didn't do much today.",
    ],
  },
  restaurant: {
    id: "restaurant",
    emoji: "🍽️",
    titleEN: "Restaurant",
    titlePT: "Restaurante",
    descriptionPT: "Peça comida, pergunte sobre o cardápio",
    difficulty: "beginner",
    starterMessage:
      "Welcome to The Blue Table! I'm Emma, your server tonight. Can I start you with something to drink, or are you ready to order?",
    vocabularyHints: ["I'd like to have", "could I get", "what do you recommend", "is it spicy", "on the side", "the check please"],
    phraseSuggestions: [
      "I'd like to order, please.",
      "Could I have the menu?",
      "What do you recommend?",
      "I'll have the..., please.",
      "Is it spicy?",
      "I'm vegetarian.",
      "I'm allergic to...",
      "No onions, please.",
      "Could I have water, please?",
      "The check, please.",
      "It was delicious, thank you!",
    ],
  },
  shopping: {
    id: "shopping",
    emoji: "🛍️",
    titleEN: "Shopping",
    titlePT: "Compras",
    descriptionPT: "Compre roupas e pergunte sobre tamanhos",
    difficulty: "beginner",
    starterMessage:
      "Hi there! Welcome to the store. Are you looking for anything specific today, or just browsing?",
    vocabularyHints: ["do you have this in", "size", "fits well", "on sale", "try it on", "receipt", "exchange"],
    phraseSuggestions: [
      "I'm just looking, thanks.",
      "Do you have this in size medium?",
      "Can I try this on?",
      "Where is the fitting room?",
      "It's too big / too small.",
      "It fits perfectly!",
      "How much is this?",
      "Is this on sale?",
      "I'll take it!",
      "Can I pay by card?",
      "Can I exchange this?",
    ],
  },
  doctor: {
    id: "doctor",
    emoji: "🏥",
    titleEN: "Doctor's Visit",
    titlePT: "Médico",
    descriptionPT: "Descreva sintomas e entenda conselhos médicos",
    difficulty: "intermediate",
    starterMessage:
      "Good morning! I'm Doctor Emma. What brings you in today? Tell me how you've been feeling.",
    vocabularyHints: ["I've been feeling", "it hurts when", "for about", "sharp pain", "dull ache", "on and off", "symptoms"],
    phraseSuggestions: [
      "I haven't been feeling well.",
      "I have a headache.",
      "My throat hurts.",
      "I have a fever.",
      "I feel very tired.",
      "It hurts here.",
      "It started two days ago.",
      "I'm taking medication for...",
      "I'm allergic to penicillin.",
      "How long do I need to rest?",
      "Do I need a prescription?",
    ],
  },
  travel: {
    id: "travel",
    emoji: "✈️",
    titleEN: "Travel & Airport",
    titlePT: "Viagem",
    descriptionPT: "Reserve passagens e navegue por aeroportos",
    difficulty: "intermediate",
    starterMessage:
      "Hello! Welcome to check-in. May I see your passport? Are you checking any bags today?",
    vocabularyHints: ["boarding pass", "carry-on", "departure gate", "layover", "connecting flight", "customs"],
    phraseSuggestions: [
      "Here is my passport.",
      "I have one bag to check.",
      "This is my carry-on.",
      "Where is gate B12?",
      "What time does boarding start?",
      "My flight was delayed.",
      "I missed my connection.",
      "I need a window seat.",
      "Where is the baggage claim?",
      "I can't find my luggage.",
    ],
  },
  work: {
    id: "work",
    emoji: "💼",
    titleEN: "Work & Career",
    titlePT: "Trabalho",
    descriptionPT: "Reuniões, entrevistas e conversas no trabalho",
    difficulty: "intermediate",
    starterMessage:
      "Good morning! Thanks for coming in. I'm Emma from HR. Please, have a seat — tell me about your professional background.",
    vocabularyHints: ["I have experience in", "I'm responsible for", "deadline", "collaborate", "in my previous role", "accomplish"],
    phraseSuggestions: [
      "I have 5 years of experience.",
      "I work in the field of...",
      "I'm responsible for...",
      "My strength is...",
      "I work well in a team.",
      "I'm good at problem-solving.",
      "In my previous job, I...",
      "I'm looking for new challenges.",
      "What are the working hours?",
      "When would I start?",
    ],
  },
  "movies-tv": {
    id: "movies-tv",
    emoji: "🎬",
    titleEN: "Movies & TV Shows",
    titlePT: "Filmes e Séries",
    descriptionPT: "Fale sobre filmes, séries e entretenimento",
    difficulty: "intermediate",
    starterMessage:
      "Hey! Have you watched anything good lately? I just finished an amazing series and I can't stop thinking about it!",
    vocabularyHints: ["plot twist", "character development", "binge-watch", "cliffhanger", "highly recommend", "overrated", "genre"],
    phraseSuggestions: [
      "I love thriller / mystery series.",
      "I've been watching...",
      "I binge-watched it in two days!",
      "The plot twist was amazing!",
      "I highly recommend it.",
      "The ending was disappointing.",
      "My favorite genre is...",
      "I don't like horror movies.",
      "Have you seen...?",
      "It's on Netflix.",
    ],
  },
};

export const TOPICS_LIST = Object.values(TOPICS);

export function getTopicById(id: TopicId): Topic {
  return TOPICS[id];
}
